version: "3.9"

services:
  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile

    image: aws-devops-react:1.0.0

    container_name: react-app

    ports:
      - "8080:80"

    restart: unless-stopped